// Generated by gencpp from file moving/hello.msg
// DO NOT EDIT!


#ifndef MOVING_MESSAGE_HELLO_H
#define MOVING_MESSAGE_HELLO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moving
{
template <class ContainerAllocator>
struct hello_
{
  typedef hello_<ContainerAllocator> Type;

  hello_()
    : myData()  {
    }
  hello_(const ContainerAllocator& _alloc)
    : myData(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _myData_type;
  _myData_type myData;




  typedef boost::shared_ptr< ::moving::hello_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moving::hello_<ContainerAllocator> const> ConstPtr;

}; // struct hello_

typedef ::moving::hello_<std::allocator<void> > hello;

typedef boost::shared_ptr< ::moving::hello > helloPtr;
typedef boost::shared_ptr< ::moving::hello const> helloConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moving::hello_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moving::hello_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace moving

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'moving': ['/home/juzhan/ros/workspace/my_ws/src/moving/msg', '/home/juzhan/ros/workspace/my_ws/src/moving/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::moving::hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moving::hello_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moving::hello_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moving::hello_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moving::hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moving::hello_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moving::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "319d8b4b8bf8dbac63eb8b2643cce814";
  }

  static const char* value(const ::moving::hello_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x319d8b4b8bf8dbacULL;
  static const uint64_t static_value2 = 0x63eb8b2643cce814ULL;
};

template<class ContainerAllocator>
struct DataType< ::moving::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moving/hello";
  }

  static const char* value(const ::moving::hello_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moving::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string myData\n\
";
  }

  static const char* value(const ::moving::hello_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moving::hello_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.myData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hello_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moving::hello_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moving::hello_<ContainerAllocator>& v)
  {
    s << indent << "myData: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.myData);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVING_MESSAGE_HELLO_H
